name: quickplay
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flex_color_scheme: ^2.1.0

  flutter_localizations:
    sdk: flutter
  font_awesome_flutter:
  kf_drawer: ^1.2.0
  drawerbehavior:
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  firebase_storage: ^3.0.8
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.6
  image_picker: ^0.8.3

  dio: ^4.0.0
  flutter_polyline_points: ^0.2.6
  google_maps_flutter: ^2.0.2

  clipboard_manager: ^0.0.4
  flutter_barcode_scanner: ^2.0.0
  barcode_widget: ^1.5.0
  lottie: ^0.6.0
  geolocator: ^8.0.5
  flutter_placeholder_textlines: ^1.1.2
  sliding_up_panel: ^2.0.0+1
  map_picker: ^0.0.3
  geocoding: ^2.0.1
  ff_navigation_bar: ^0.1.5




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0

flutter_icons:
  image_path : "assets/img/quickplaylogo.PNG"
  android : true
  ios : true

flutter_launcher_name :
  name : "QuickPlay"


flutter:
  uses-material-design: true


  assets:
    - assets/img/
    - assets/loading.json
    - assets/sportLoader.json


  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf